version: "3.7"

services:
  application:
    container_name: movies-api
    image: fbiopereira/movies-api:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      SERVICE_NAME: movies-api
      ENVIRONMENT: development
      LOG_PATH: /var/log/app/
      MONGO_URI: mongodb://root:example@mongo_service:27017/movies
    ports:
      - 5000:80
    links:
      - mongo_service:mongo_service
    depends_on:
      - mongo_service

  mongo_service:
      image: mongo:4.0.23
      restart: on-failure
      container_name: mongo_service
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: mongopwd
      ports:
        - 27017:27017
